In [30]:
import numpy as np
from sklearn.linear_model import LinearRegression
# 上面八元一次方程对应的X数据  # 对应的y [ 339 -114 30 126 -395 -87 422 -309]
X =np.array([[ 0, 14, 8 ,0 ,5, -2, 9 ,-3],
             [ -4, 10, 6, 4 ,-14, -2, -14, 8],
             [ -1, -6, 5 ,-12, 3 ,-3, 2, -2],
             [ 5, -2, 3, 10, 5 ,11 ,4 ,-8],
             [-15, -15, -8, -15, 7 ,-4, -12, 2],
             [ 11, -10, -2, 4, 3, -9, -6, 7],
             [-14, 0, 4 ,-3, 5 ,10, 13, 7],
             [ -3, -7, -2, -8, 0 ,-6, -5, -9]])
y= np.array([339,-114,30,126,-395,-87,422,-309])
display(X,y)

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])

array([ 339, -114,   30,  126, -395,  -87,  422, -309])

In [31]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

0.0

In [32]:
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

In [33]:
# 八元一次方程添加截距


$\hat{y} = w_1X_1 + w_2X_2+.....+w_nX_n+ b$

$\hat{y} = w_1X_1 + w_2X_2+.....+w_nX_n+ w_0 *1$

In [34]:
# 向后面增加一列
# X=np.concatenate([X,np.full(shape=(8,1),fill_value=1)],axis=1)
# X

In [35]:
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)


array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

In [36]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
print(model.coef_,model.intercept_)

[ 1.  5. 15.  3.  8.  4. 17. 12.] 0.0


In [37]:
X.shape

(8, 8)

In [38]:
#增加一个方程

In [39]:
w = np.array([1,5,15,3,8,4,17,12])
w

array([ 1,  5, 15,  3,  8,  4, 17, 12])

In [40]:
X9= np.random.randint(-15,15,size=8)
X9

array([ 10,   9,  10,   1, -10,  10,   6, -13])

In [41]:
X9.dot(w)+12

y =np.concatenate([y,[-283]])
y
X9=np.concatenate([X9,[1]])
X9

array([ 10,   9,  10,   1, -10,  10,   6, -13,   1])

In [42]:
# np.concatenate([X,[X9]])
X

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])