In [1]:
import numpy as np
l= [1,2,34,4]
arr =np.array(l)
arr

array([ 1,  2, 34,  4])

我们可以利用np中的一些内置函数来创建数组，比如我们创建全0的数组，也可以创建全1数组，全是其
他数字的数组，或者等差数列数组，正态分布数组，随机数。


In [4]:
import numpy as np
arr1 =np.ones(10)
arr2 = np.ones(10)
arr3 = np.full(shape =[2,3],fill_value=2.718)
arr3
arr4 = np.arange(start =0 ,stop=20,step=2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

数组的轴数 维度

In [8]:
import numpy as np
arr = np.random.randint(0,100,size =(3,4,5))
arr.ndim
arr.shape
arr.size
arr.dtype

dtype('int64')

IO操作

In [9]:
x= np.random.randn(5)
y =np.arange(0,10,1)
np.save("x_arr",x)
np.savez("some_array.npz",xarr  =x ,yarr=y)


In [10]:
np.load("x_arr.npy")
np.load("some_array.npz")["yarr"]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#存储到csv txt文件中
arr = np.random.randint(0,10,size=(3,4))
np.savetxt("arr.csv",arr,delimiter=",")
np.loadtxt("arr.csv",delimiter=",",dtype =np.int32)


array([[0, 4, 0, 2],
       [9, 4, 4, 4],
       [1, 3, 1, 1]], dtype=int32)