In [2]:
import numpy as np
a =np.random.randint(0,100,size=(4,5))
b= a
a is b
# 返回true a 和b是两个不同名字对应一个内存对象
b[0,0]= 1024
display(a,b)

array([[1024,   39,    9,   53,   97],
       [  82,   46,   70,   17,   20],
       [  68,   10,   16,   39,   33],
       [  47,   94,   59,   48,   84]])

array([[1024,   39,    9,   53,   97],
       [  82,   46,   70,   17,   20],
       [  68,   10,   16,   39,   33],
       [  47,   94,   59,   48,   84]])

In [7]:
# 查看或者浅拷贝
a =np.random.randint(0,100,size=(4,5))
b =a.view()  # 使用a中的数据创建一个新数组
a is b# 返回False a和b是两个不同名字对应同一个内存对象
b.base is a # 数据一样
b.flags.owndata
a.flags.owndata
b[0,0]= 1024
display(a,b)


array([[1024,   49,   23,   70,    3],
       [  44,   75,    6,   92,   48],
       [  80,    8,   97,   49,    0],
       [  22,   94,   16,   80,   46]])

array([[1024,   49,   23,   70,    3],
       [  44,   75,    6,   92,   48],
       [  80,    8,   97,   49,    0],
       [  22,   94,   16,   80,   46]])

In [8]:
import numpy as np
a = np.random.randint(0,100,size = (4,5))
b = a.copy()
b is a # 返回False
b.base is a
# 返回False
b.flags.owndata
# 返回True
a.flags.owndata # 返回True
b[0,0] = 1024 # b改变，a不变，分道扬镳
display(a,b)

array([[34, 39, 90, 19, 97],
       [19, 15, 84, 91, 95],
       [54, 69,  9, 47, 34],
       [ 7, 31, 19, 45, 81]])

array([[1024,   39,   90,   19,   97],
       [  19,   15,   84,   91,   95],
       [  54,   69,    9,   47,   34],
       [   7,   31,   19,   45,   81]])