In [4]:
import numpy as np
arr1 = np.random.randint(0,10,size=(3,4,5))
arr1
arr2 = arr1.reshape(12,5)
arr2

array([[3, 1, 9, 8, 6],
       [1, 7, 6, 5, 9],
       [9, 7, 1, 1, 7],
       [9, 6, 7, 8, 1],
       [5, 3, 5, 5, 6],
       [3, 7, 6, 8, 8],
       [1, 8, 7, 3, 9],
       [7, 3, 2, 2, 6],
       [8, 4, 4, 3, 3],
       [7, 4, 8, 0, 9],
       [0, 6, 7, 9, 6],
       [2, 2, 5, 9, 3]])

In [6]:
# 数组转置
arr1 =np.random.randint(0,10,size=(3,5))
arr1.shape
arr1.T



array([[5, 2, 5],
       [9, 4, 3],
       [6, 5, 9],
       [3, 4, 2],
       [8, 3, 9]])

In [7]:
# 数组堆叠
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,5])
np.concatenate([arr1,arr2],axis=0)
#axis表示第一维串联


array([1, 2, 3, 2, 4, 5])